### ISSUE TITLE
add JQuery dependency

### ISSUE THREAD

**Issue by gravitational-dark-light** [bitWolfy/Redesign-Fixes#31]
On waterfox classic with violent monkey, the userscript breaks because it can't find JQuery

to solve this, I had to add `@require      https://code.jquery.com/jquery-3.4.1.js` to the metadata block

Can you please fix it?

**Comment by bitWolfy** [comment]
That's odd. I didn't feel the need to load jQuery because the site already does that.
Still, not a big deal. Added it in #32 (2.0.8).
